#!/usr/bin/python3
#SODX-FileCopyrrightText: 2023 harutaka sato s22c1058@s.chibakoudai.jp
#SPDX-license-Identifier: GPL-3.0
import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += float(line)
    except:
        ans += float(line)

print(ans)
*このソフトウェアパッケージは，3条項BSDライセンスの下，再頒布および使用が許可されます．
*このパッケージは，aaa由来のコード（© 2022 Hoge Fuge）を利用しています．
*このパッケージのコードは，下記のスライド（CC-BY-SA 4.0 by Ryuichi Ueda）のものを，本人の許可を得て自身の著作としたものです．
*[ryuichiueda/my_slides robosys_2022](https://github.com/ryuichiueda/my_slides/tree/master/robosys_2022)
*© 2023 Harutaka Sato
