#!/usr/bin/python3
#SODX-FileCopyrrightText: 2023 harutaka sato s22c1058@s.chibakoudai.jp
#SPDX-license-Identifier: GPL-3.0
import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += float(line)
    except:
        ans += float(line)

print(ans)
